


-- auto-generated definition
create table patient
(
    id            integer generated by default as identity
        constraint patient_pkey
            primary key,
    date_of_birth date,
    gender        varchar(255),
    phone_number  varchar(255),
    user_id       integer not null
);

alter table patient
    owner to postgres;

-- auto-generated definition
create table shift
(
    id           integer generated by default as identity
        constraint shift_pkey
            primary key,
    date         date,
    doctor_id    integer not null,
    end_time     time,
    procedure_id integer not null,
    start_time   time
);

alter table shift
    owner to postgres;


-- auto-generated definition
create table appointment
(
    shift_id   integer not null
        constraint uk_hceh1f14irmc0x37f7bfulmo2
            unique
        constraint fkr3dgxvrvoonmuaopg4w8ifugs
            references shift,
    patient_id integer not null
        constraint fk4apif2ewfyf14077ichee8g06
            references patient,
    constraint appointment_pkey
        primary key (patient_id, shift_id)
);

alter table appointment
    owner to postgres;






