spring:
  application:
    name: security-service
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://34.118.81.171:3306/users_db}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
jwt:
  token:
    secret: hospitalsecrettt
server:
  port: 8077

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost