
-- auto-generated definition
create table hospital
(
    id      integer generated by default as identity
        constraint hospital_pkey
            primary key,
    address varchar(255),
    name    varchar(255)
);

alter table hospital
    owner to postgres;

-- auto-generated definition
create table person
(
    id          integer generated by default as identity
        constraint person_pkey
            primary key,
    first_name  varchar(255),
    password    varchar(255),
    role_id     integer not null,
    second_name varchar(255),
    user_name   varchar(255)
);

alter table person
    owner to postgres;
-- auto-generated definition
create table speciality
(
    id              integer generated by default as identity
        constraint speciality_pkey
            primary key,
    speciality_name varchar(255)
);

alter table speciality
    owner to postgres;
-- auto-generated definition
create table doctor
(
    id            integer generated by default as identity
        constraint doctor_pkey
            primary key,
    phone_number  varchar(255),
    user_id       integer not null,
    speciality_id integer
        constraint fkdht1k3ou6ody790hip20bl9dx
            references speciality
);

alter table doctor
    owner to postgres;
-- auto-generated definition
create table room
(
    room_number bigint,
    hospital_id integer not null
        constraint fksc1y77urc7knjy3bf7ssr46bk
            references hospital,
    doctor_id   integer not null
        constraint uk_g7q5b45jwv4q15js8msilmii1
            unique
        constraint fkm7unmvas79cm9ry7ffds1rxv9
            references doctor,
    constraint room_pkey
        primary key (doctor_id, hospital_id)
);

alter table room
    owner to postgres;




-- auto-generated definition
create table procedure
(
    id             bigint generated by default as identity
        constraint procedure_pkey
            primary key,
    procedure_name varchar(255),
    speciality_id  bigint
        constraint fk56rucj7tofhe97iqjt1khyr1u
            references speciality
);

alter table procedure
    owner to postgres;
